services:
  # Backend API Service
  - type: web
    name: sword-game-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /

  # Frontend Static Site
  - type: web
    name: sword-game-frontend
    runtime: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: sword-game-backend
          envVarKey: RENDER_EXTERNAL_URL
